PROTOCOL_NAME = "RAMP-UDP"
PROTOCOL_VERSION = 1

MAGIC_NUMBER = b"RM"

HEADER_SIZE = 10

MAX_PAYLOAD_SIZE = 1024
BUFFER_SIZE = 2048
MAX_OUT_OF_ORDER_BUFFER_SIZE = 128

DEFAULT_TIMEOUT = 2.0
MAX_RETRANSMISSIONS = 5

HMAC_SIZE = 32